chainstacklabs/chainbench

- .github/workflows/checks.yml
- .github/workflows/python-publish.yml
This PR introduces a workflow for building and publishing the package to PyPI. It also adds matrix version usage to the Checks workflow.
> Update GitHub actions

- pyproject.toml
> Update to v0.3.2

- chainbench/main.py
- chainbench/profile/avalanche/general.py
- chainbench/profile/bsc/general.py
- chainbench/profile/ethereum/general.py
- chainbench/profile/evm/get_logs.py
- chainbench/profile/evm/heavy.py
- chainbench/profile/evm/light.py
- chainbench/profile/oasis/general.py
- chainbench/profile/polygon/general.py
- chainbench/test_data/base.py
- chainbench/test_data/evm.py
- chainbench/user/base.py
- chainbench/user/evm.py
- chainbench/util/rng.py
- docs/PROFILE.md
- pyproject.toml
For benchmarking purposes, test data should be fairly consistent between runs. test_data modules have been refactored for that purpose.
- added --version command
- added RNGManager and RNG helper classes
- Random Number Generators are now unique for each jsonrpc method/task
- test_data now fetches random blocks from a pre-defined block range, with a fixed seed so that each run is the same.
- updated profile.md to reflect changes
- update version to 0.4.0
> make test data generation more consistent

- chainbench/profile/starknet/wallet.py
- chainbench/test_data/evm.py
- chainbench/test_data/starknet.py
- chainbench/user/base.py
- chainbench/user/starknet.py
- chainbench/util/rpc.py
- refactor `test_data\evm.py` and a little to enable `test_data\starknet.py` to inherit from `EVMTestData` class and reduce code duplication
- add `url_postfix` argument to `_post` and `make_call` in user\base.py
- add starknet wallet profile
- add `StarkNetTestData` and `StarkNetBenchUser` classes
> CORE-9556 Add StarkNet Support

- chainbench/profile/starknet/wallet.py
- chainbench/test_data/starknet.py
- chainbench/user/starknet.py
- fix starknet_call and starknet_estimateFee params
- fix _fetch_latest_block_number returning hex instead of int
> fix starknet issues

- chainbench/test_data/__init__.py
- chainbench/test_data/base.py
- chainbench/user/base.py
- chainbench/user/evm.py
- chainbench/user/starknet.py
- chainbench/util/monitor.py
- some minor refactoring and bugfixes
- mistake in defining test data sizes
> Minor refactoring and bugfixes

- README.md
- chainbench/profile/avalanche/general.py
- chainbench/profile/bsc/general.py
- chainbench/profile/ethereum/general.py
- chainbench/profile/evm/debug_trace.py
- chainbench/profile/evm/get_logs.py
- chainbench/profile/evm/heavy.py
- chainbench/profile/evm/light.py
- chainbench/profile/polygon/general.py
- chainbench/profile/solana/general.py
- chainbench/test_data/base.py
- renaming some profiles
- add XS size and shift sizes so each size is now one size larger than before
> Minor refactoring

- README.md
- chainbench/main.py
- chainbench/profile/evm/all.py
- chainbench/test_data/base.py
- chainbench/test_data/dummy.py
- chainbench/test_data/evm.py
- chainbench/test_data/solana.py
- chainbench/test_data/starknet.py
- chainbench/tools/test_method.py
- chainbench/user/base.py
- chainbench/user/evm.py
- chainbench/user/solana.py
- chainbench/user/starknet.py
- chainbench/util/cli.py
- chainbench/util/event.py
- chainbench/util/monitor.py
- chainbench/util/rng.py
- chainbench/util/rpc.py
- chainbench/util/timer.py
- pyproject.toml
- support running tests by method and by directory containing multiple load profiles
- support method and load profile selection when running in Web UI mode
- add validation to method argument, profile option and profile_dir option
- refactor clients command under list command
- add list methods and list profiles commands
- added evm.all profile utilizing all methods defined in EVMMethods class
- support more than 1 level of sub-directory for profiles
- bump version to 0.5.0
> New Feature: Test single method and Test with directory containing multiple load profile files

- pyproject.toml
> bump version to 0.5.1

- .github/workflows/docker-publish.yml
- Dockerfile
Modify docker publish workflow to publish to dockerhub
> Modify workflow to publish to dockerhub

- chainbench/tools/discovery/clients.json
- chainbench/tools/discovery/methods.json
- add support for zksyncera client for method discovery tool
> add zksync to discovery tool

- chainbench/test_data/blockchain.py
- chainbench/test_data/evm.py
- chainbench/test_data/solana.py
- chainbench/test_data/starknet.py
- chainbench/util/event.py
- add tracking of invalid blocks and fetch new ones when invalid blocks are encountered
- fix issue with "error" keyerror in jsonrpc response
> fix blocks with zero tx

- chainbench/user/http.py
- fix issue with "error" keyerror
- "error" keyerror when "error" falsely detected in response
> fix issue with "error" keyerror

- Dockerfile
- add frequently used apps - htop and nano
> Update Dockerfile - add nano and htop

- .github/workflows/checks.yml
- .github/workflows/python-publish.yml
- README.md
- Update github actions versions
> Update Github Actions 

- chainbench/main.py
- chainbench/util/cli.py
- poetry.lock
- pyproject.toml
- add locust-plugins[dashboard] in dependencies
- use meaningful test plan names for timescale dashboard
- restore missing dependencies for timescale dashboard
> Timescale dashboard fixes

- chainbench/user/methods/evm.py
- add debug_getBadBlocks, debug_getRawBlock, debug_getRawHeader, debug_getRawReceipts, debug_getRawTransaction, debug_traceBadBlock, debug_traceBlock, debug_traceBlockByHash.
> add evm debug trace methods

- chainbench/test_data/ethereum.py
- chainbench/test_data/evm.py
- chainbench/user/http.py
- chainbench/user/methods/ethereum.py
- chainbench/util/event.py
- add smart contract addresses for ethereum-sepolia-testnet
- small fixes for ethereum beacon api
> various fixes/improvements

- poetry.lock
- pyproject.toml
- update locust to 2.24.1
- update locust-plugins to 4.4.2
> Update locust and locust-plugins

- chainbench/main.py
- chainbench/profile/ethereum/general.py
- fix debug trace tasks not being optional
- fix trace transaction in ethereum.general profile having missing params
> fix trace transaction

- pyproject.toml
> bump version to 0.6.6

- chainbench/util/http.py
- add basic auth support, e.g. specifying target as `https://username:password@targeturl.com`
> add basic auth support

- chainbench/profile/arbitrum/general.py
- chainbench/profile/avalanche/archive.py
- chainbench/profile/avalanche/general.py
- chainbench/profile/base/archive.py
- chainbench/profile/base/general.py
- chainbench/profile/fantom/archive.py
- chainbench/profile/fantom/general.py
- chainbench/profile/optimism/archive.py
- chainbench/profile/optimism/general.py
- chainbench/profile/ronin/general.py
- chainbench/user/methods/evm.py
- add profiles for arbitrum, base, fantom, optimism, ronin
- update avalanche general profile
- add debug and trace tags in EvmMethods class for relevant tasks
> Add profiles for arbitrum, avalanche, base, fantom, optimism, ronin

- chainbench/test_data/evm.py
> add zksync-era support

- chainbench/profile/evm/debug_trace.py
- revert temporary change to debug_trace profile
> revert temporary change to debug_trace profile

- chainbench/profile/gnosis/archive.py
- chainbench/profile/gnosis/general.py
- chainbench/user/protocol/evm.py
- add gnosis profiles
- fix errors with trace_callMany
> Add gnosis profiles

- chainbench/user/protocol/evm.py
- fix incorrect params for replay block transactions
> fix incorrect params for replay block transactions

- chainbench/test_data/evm.py
- chainbench/user/http.py
add scroll chain id and contracts for mainnet and sepolia testnet
> Add Scroll support

- README.md
- chainbench/main.py
- chainbench/shapes/spike.py
- chainbench/shapes/step.py
- chainbench/user/http.py
- chainbench/user/jsonrpc.py
- chainbench/user/protocol/ethereum.py
- chainbench/util/cli.py
- chainbench/util/http.py
- poetry.lock
- pyproject.toml
- add support for load shapes
- add load shapes for step load and spike patterns
- update dependencies
- update README.md
> add support for load shapes

- README.md
- chainbench/main.py
- chainbench/util/cli.py
- add another option for specifying profile via an absolute profile path to load profile file (locustfile).
https://github.com/chainstacklabs/chainbench/issues/108
> add --profile-path flag
